"""Type stubs for the native Rust extension module."""

from __future__ import annotations

import datetime
from collections.abc import Iterator
from typing import Any

class PintError(ValueError): ...
class DimensionalityError(PintError): ...
class UndefinedUnitError(PintError): ...
class OffsetUnitCalculusError(PintError): ...
class DefinitionSyntaxError(PintError): ...
class RedefinitionError(PintError): ...

class Unit:
    def __init__(self, units: str) -> None: ...
    @property
    def dimensionality(self) -> str: ...
    @property
    def dimensionless(self) -> bool: ...
    def is_compatible_with(self, other: Unit | str) -> bool: ...
    def compatible_units(self) -> list[str]: ...
    def from_(self, quantity: Quantity) -> Quantity: ...
    def m_from(self, quantity: Quantity) -> float: ...
    @property
    def systems(self) -> list[str]: ...
    def compare(self, other: Unit, op: str) -> bool: ...
    def _units_str(self) -> str: ...
    def _units_dict(self) -> list[tuple[str, float]]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __mul__(self, other: Unit | float) -> Unit | Quantity: ...
    def __rmul__(self, other: Unit | float) -> Unit | Quantity: ...
    def __truediv__(self, other: Unit) -> Unit: ...
    def __pow__(self, exp: float) -> Unit: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __copy__(self) -> Unit: ...
    def __deepcopy__(self, memo: object) -> Unit: ...
    def __reduce__(self) -> tuple[type, tuple[str]]: ...

class Quantity:
    def __init__(
        self,
        value: float | str | Quantity,
        units: str | None = None,
    ) -> None: ...
    @property
    def magnitude(self) -> float: ...
    @property
    def m(self) -> float: ...
    @property
    def units(self) -> Unit: ...
    @property
    def u(self) -> Unit: ...
    @property
    def dimensionality(self) -> str: ...
    @property
    def dimensionless(self) -> bool: ...
    @property
    def unitless(self) -> bool: ...
    def m_as(self, units: str) -> float: ...
    def to(self, units: str) -> Quantity: ...
    def ito(self, units: str) -> None: ...
    def to_base_units(self) -> Quantity: ...
    def to_root_units(self) -> Quantity: ...
    def ito_base_units(self) -> None: ...
    def ito_root_units(self) -> None: ...
    def to_compact(self) -> Quantity: ...
    def to_reduced_units(self) -> Quantity: ...
    def ito_reduced_units(self) -> None: ...
    def to_preferred(
        self,
        preferred_units: list[str] | None = None,
    ) -> Quantity: ...
    def ito_preferred(
        self,
        preferred_units: list[str] | None = None,
    ) -> None: ...
    def to_unprefixed(self) -> Quantity: ...
    def ito_unprefixed(self) -> None: ...
    def to_tuple(self) -> tuple[float, list[tuple[str, float]]]: ...
    @staticmethod
    def from_tuple(
        tup: tuple[float, list[tuple[str, float]]],
    ) -> Quantity: ...
    def unit_items(self) -> list[tuple[str, float]]: ...
    def compare(self, other: Quantity, op: str) -> bool: ...
    def to_timedelta(self) -> datetime.timedelta: ...
    def plus_minus(self, error: float) -> Any: ...
    def check(self, dimension: str) -> bool: ...
    def is_compatible_with(
        self,
        other: Quantity | Unit | str,
    ) -> bool: ...
    def compatible_units(self) -> list[str]: ...
    def _units_str(self) -> str: ...
    def _units_dict(self) -> list[tuple[str, float]]: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __format__(self, spec: str) -> str: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __neg__(self) -> Quantity: ...
    def __abs__(self) -> Quantity: ...
    def __round__(self, ndigits: int | None = None) -> Quantity: ...
    def __add__(self, other: Quantity | float) -> Quantity: ...
    def __radd__(self, other: Quantity | float) -> Quantity: ...
    def __sub__(self, other: Quantity | float) -> Quantity: ...
    def __rsub__(self, other: Quantity | float) -> Quantity: ...
    def __mul__(self, other: Quantity | Unit | float) -> Quantity: ...
    def __rmul__(self, other: Quantity | Unit | float) -> Quantity: ...
    def __truediv__(
        self,
        other: Quantity | Unit | float,
    ) -> Quantity: ...
    def __rtruediv__(self, other: float) -> Quantity: ...
    def __pow__(self, exp: float) -> Quantity: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: Quantity) -> bool: ...
    def __le__(self, other: Quantity) -> bool: ...
    def __gt__(self, other: Quantity) -> bool: ...
    def __ge__(self, other: Quantity) -> bool: ...
    def __hash__(self) -> int: ...
    def __copy__(self) -> Quantity: ...
    def __deepcopy__(self, memo: object) -> Quantity: ...
    def __reduce__(self) -> tuple[type, tuple[float, str]]: ...

# Use _Q and _U aliases inside UnitRegistry to avoid mypy confusing
# the Quantity/Unit method names with the Quantity/Unit class types.
_Q = Quantity
_U = Unit

class UnitRegistry:
    def __init__(self) -> None: ...
    def Quantity(  # noqa: N802
        self,
        value: float | str | _Q,
        units: str | None = None,
    ) -> _Q: ...
    def Unit(self, units: str) -> _U: ...  # noqa: N802
    def parse_expression(self, expr: str) -> _Q: ...
    def parse_units(self, units: str) -> _U: ...
    def convert(self, value: float, src: str, dst: str) -> float: ...
    def define(self, definition: str) -> None: ...
    def get_compatible_units(self, unit: str) -> list[str]: ...
    def get_base_units(self, unit: str) -> tuple[float, _U]: ...
    def get_root_units(self, unit: str) -> tuple[float, _U]: ...
    def get_dimensionality(self, unit: str) -> str: ...
    def get_name(self, unit: str) -> str: ...
    def get_symbol(self, unit: str) -> str: ...
    def is_compatible_with(self, unit1: str, unit2: str) -> bool: ...
    def parse_unit_name(
        self,
        unit: str,
    ) -> list[tuple[str, str, str]]: ...
    def load_definitions(self, definition: str) -> None: ...
    @property
    def default_format(self) -> str: ...
    @property
    def auto_reduce_dimensions(self) -> bool: ...
    def _get_conversion_factor(self, src: str, dst: str) -> float: ...
    def _get_root_units(self, unit: str) -> tuple[float, str]: ...
    def _get_dimensionality(self, unit: str) -> str: ...
    def _format_units(self, unit: str) -> str: ...
    def _get_prefixes(self) -> list[tuple[str, float]]: ...
    def __contains__(self, item: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getattr__(self, name: str) -> _Q: ...
